brain_two/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("todos.urls")),
]

todos/urls.py
from django.urls import path

from todos.views import (
  TodoListView,
  TodoListDetailView,
  TodoListCreateView,
  TodoItemCreateView,
  TodoListDeleteView,
  TodoListUpdateView,
  TodoItemUpdateView,
  )


urlpatterns = [
    path("", TodoListView.as_view(), name="todo_list"),
    path("<int:pk>/", TodoListDetailView.as_view(), name="todo_detail"),
    path("new/", TodoListCreateView.as_view(), name="todo_new"),
    path("items/new/", TodoItemCreateView.as_view(), name="todo_item_new"),
    path("<int:pk>/items/edit/", TodoItemUpdateView.as_view(), name="todo_item_edit"),
    path("<int:pk>/edit/", TodoListUpdateView.as_view(), name="todo_edit"),
    path("<int:pk>/delete/", TodoListDeleteView.as_view(), name="todo_delete"),
]

todos/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class TodoList(models.Model):
  name = models.CharField(unique=True, max_length=100)
  created_on = models.DateTimeField(auto_now_add=True)

  def __str__(self):
      return self.name


class TodoItem(models.Model):
  task = models.CharField(max_length=100)
  due_date = models.DateTimeField(blank=True, default=timezone.now, null=True)
  is_completed = models.BooleanField(null=False, default=False)
  list = models.ForeignKey(
    'ToDoList',
    related_name="items",
    on_delete=models.CASCADE,
  )

  def __str__(self):
      return self.task

todos/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from todos.models import TodoList, TodoItem

# Create your views here.
class TodoListView(ListView):
  model = TodoList
  template_name = "todos/list.html"

  def get(self, request, *args, **kwargs):
    response = super(ListView, self).get(request, *args, **kwargs)
    response.status_code = 200
    return response


class TodoListDetailView(DetailView):
  model = TodoList
  template_name = "todos/detail.html"

  def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class TodoListCreateView(CreateView):
  model = TodoList
  template_name = "todos/new.html"
  fields = ['name']
  success_url = reverse_lazy("todo_list")


class TodoListDeleteView(DeleteView):
  model = TodoList
  template_name = "todos/delete.html"
  success_url = reverse_lazy("todo_list")


class TodoListUpdateView(UpdateView):
  model = TodoList
  template_name = "todos/edit.html"
  fields = ['name']
  success_url = reverse_lazy("todo_list")


class TodoItemCreateView(CreateView):
  model = TodoItem
  template_name = "items/new.html"
  fields = ['task', 'due_date', 'is_completed', 'list']
  success_url = reverse_lazy("todo_list")


class TodoItemUpdateView(UpdateView):
  model = TodoItem
  template_name = "items/edit.html"
  fields = ['task', 'due_date', 'is_completed', 'list']
  success_url = reverse_lazy("todo_list")

  # TodoListCreateView,
  # TodoItemCreateView,
  # TodoDeleteView,
  # TodoUpdateView,

todos/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ToDo</title>
    <link rel="stylesheet" href="" />
  </head>

  <body>
    <header>

    </header>
    <main>{% block content %} {% endblock content %}</main>
    <footer></footer>
  </body>
</html>

todos/templates/items/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

todos/templates/items/new.html
{% extends 'base.html' %}

{% block content %}
<main class="">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="">
      <button class="">Create</button>
    </div>
  </form>
</main>
{% endblock content %}

todos/templates/todos/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
  <form method="post">
    {% csrf_token %}
    <h2>Delete {{ todolist }}?</h2>
    {{ form.as_p }}
    <div class="control">
      <button class="button">Delete</button>
    </div>
  </form>
</main>
{% endblock content %}

todos/templates/todos/detail.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div>
    <a href="{% url 'todo_list' %}">Back to list</a>
    <a href="{% url 'todo_delete' todolist.id %}">Delete</a>
    <a href="{% url 'todo_edit' todolist.id %}">Edit</a>
  </div>
<h1>{{ todolist.name }}</h1>
<h2>Tasks</h2>
  <table>
    <thead>
      <tr>
        <th>Task</th>
        <th>Due date</th>
      </tr>
    </thead>
    <tbody>
      {% for item in todolist.items.all %}
        <tr>
          <td><a href="{% url 'todo_item_edit' item.id %}">{{ item.task }}</a></td>
          <td>{{ item.due_date|date:"M d, Y"}}</td>
        </tr>
     {% endfor %}
    </tbody>
  </table>
</main>
{% endblock content %}

todos/templates/todos/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

todos/templates/todos/list.html
{% extends 'base.html' %}

{% block content %}
<main>
  <h1>My lists</h1>
  <a href="{% url 'todo_new' %}">Create a new list</a>
  <a href="{% url 'todo_item_new' %}">Create a new item</a>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of items</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todolist_list %}
      <tr>
        <td><a href="{% url 'todo_detail' todo.id %}">{{ todo }}</a></td>
        <td>{{ todo.items.all|length }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</main>
{% endblock content %}

todos/templates/todos/new.html
{% extends 'base.html' %}

{% block content %}
<main class="">
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <div class="">
      <button class="">Create</button>
    </div>
  </form>
</main>
{% endblock content %}